blueprint:
  name: Notification to turn off device after some time turned on
  description: Sends an alert when a device has been running for more than a specified amount of time. Includes options to turn off the device or reset the timer.
  domain: automation
  input:
    device_entity:
      name: Device Entity
      description: The entity of the device to monitor (e.g., climate.living_room_ac, switch.fan_living_room)
      selector:
        entity:
    trigger_state:
      name: Trigger State
      description: The state the device needs to be in to start the timer (e.g., 'on', 'cooling', 'heating', etc.)
      default: 'on'
      selector:
        text:
    device_timer_duration:
      name: Timer Duration
      description: The time before the alert triggers (default 3 hours)
      default: '03:00:00'
      selector:
        duration: {}

trigger:
  - platform: state
    entity_id: !input 'device_entity'
    to: !input 'trigger_state'
    for: !input 'device_timer_duration'

action:
  - service: notify.notify
    data:
      message: "⚠️ The device has been running for more than the specified duration. You can choose to turn it off or reset the timer."
      data:
        actions:
          - action: "turn_off_device"
            title: "Turn Off Device"
          - action: "reset_timer"
            title: "Reset Timer"

  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "turn_off_device"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event_data.action == 'turn_off_device' }}"
        sequence:
          - service: homeassistant.turn_off
            entity_id: !input 'device_entity'
          - service: notify.notify
            data:
              message: "The device has been turned off."

      - conditions:
          - condition: template
            value_template: "{{ trigger.event_data.action == 'reset_timer' }}"
        sequence:
          - service: timer.start
            entity_id: timer.ac_running_timer
          - service: notify.notify
            data:
              message: "The timer has been reset."
