blueprint:
  name: Device On Reminder Loop Until Off (Testable Delay)
  description: >
    When a device is turned on, wait X hours (supports fractions), then send an actionable notification
    to turn off or delay. Loops until device is off.
  domain: automation
  input:
    target_device:
      name: Target Device
      description: The switch or device to monitor
      selector:
        entity:
          domain: switch
    delay_hours:
      name: Delay Hours
      description: Number of hours to wait before sending the notification (supports decimals for testing)
      default: 0.1
      selector:
        number:
          min: 1
          max: 3600
          step: 1
          unit_of_measurement: seconds

mode: restart

trigger:
  - platform: state
    entity_id: !input target_device
    to: "on"

action:
  - repeat:
      until:
        - condition: state
          entity_id: !input target_device
          state: "off"

      sequence:
        - delay:
            seconds: !input delay_hours

        - service: notify.notify
          data:
            message: "Turn off?"
            title: "Device Still On"
            data:
              actions:
                - action: "TURN_OFF"
                  title: "Turn Off"
                - action: "DELAY"
                  title: "Remind Me Later"
              tag: "reminder-turn-off"

        - wait_for_trigger:
            - platform: event
              event_type: mobile_app_notification_action
              event_data:
                action: TURN_OFF
            - platform: event
              event_type: mobile_app_notification_action
              event_data:
                action: DELAY

        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ wait.trigger.event.data.action == 'TURN_OFF' }}"
              sequence:
                - service: switch.turn_off
                  target:
                    entity_id: !input target_device
