blueprint:
  name: Notification to turn off device after some time turned on
  description: Sends an actionable notification after a device has been on for a specified duration.
  domain: automation
  input:
    device:
      name: Device
      description: The device to monitor
      selector:
        entity:
          domain: light
    delay_seconds:
      name: Delay (Seconds)
      description: The duration (in seconds) the device must be on before sending the notification.
      default: 3
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: seconds

trigger:
  - platform: state
    entity_id: !input device
    to: "on"
    for:
      seconds: !input delay_seconds

action:
  - service: notify.notify
    data:
      message: >-
        ⚠️ The device has been running for more than {{ delay_seconds }} seconds. You
        can choose to turn it off or reset the timer.
      data:
        actions:
          - action: turn_off_device
            title: Turn Off Device
          - action: reset_timer
            title: Reset Timer

  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: turn_off_device
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: reset_timer

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.action == 'turn_off_device' }}"
        sequence:
          - service: homeassistant.turn_off
            entity_id: !input device
          - service: !input notification_entity
            data:
              message: "The device has been turned off."
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.action == 'reset_timer' }}"
        sequence:
          - service: automation.trigger
            target:
              entity_id: automation.notification_to_turn_off_device_after_some_time_turned_on
          - service: !input notification_entity
            data:
              message: >-
                ⚠️ The timer has been reset. The device has been running for more than the specified duration again.
              data:
                actions:
                  - action: turn_off_device
                    title: Turn Off Device
                  - action: reset_timer
                    title: Reset Timer
